---
sidebar: sidebar 
permalink: reference-configs-aws.html 
keywords: ec2, instance, type, explore, standard, premium, byol, capacity, maximum, virtual machine, Cloud Volumes ONTAP, supported, configurations, sizes, disks, networking, bandwidth, professional package 
summary: Se admiten varias configuraciones de Cloud Volumes ONTAP en AWS. 
---
= Configuraciones compatibles para Cloud Volumes ONTAP en AWS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se admiten varias configuraciones de Cloud Volumes ONTAP en AWS.



[[supported-number-of-nodes]]
== Número de nodos admitidos

Cloud Volumes ONTAP está disponible en AWS como un sistema de nodo único y como un par de nodos de alta disponibilidad (HA) para tolerancia a fallos y operaciones sin interrupciones.

No se admite la actualización de un sistema de nodo único a un par de HA. Si quieres cambiar entre un sistema de nodo único y un par de HA, necesitas implementar un sistema nuevo y replicar los datos del sistema existente al nuevo.



[[supported-storage]]
== Almacenamiento compatible

Cloud Volumes ONTAP admite varios tipos de discos EBS y almacenamiento de objetos S3 para la organización de datos por niveles. La capacidad máxima de almacenamiento está determinada por la licencia que elijas.



[[storage-support-by-license]]
=== Soporte de almacenamiento por licencia

Cada licencia admite una capacidad máxima del sistema diferente. La capacidad máxima del sistema incluye el almacenamiento basado en disco más el almacenamiento de objetos usado para la organización de datos por niveles. NetApp no admite que se supere este límite.

[role="tabbed-block"]
====
.Licencias basadas en capacidad
--
[cols="h,d,d"]
|===
|  | Freemium | Licencia basada en la capacidad 


 a| 
*Capacidad máxima del sistema* (discos + almacenamiento de objetos) ^1^
| 500 GiB | Flexible ^2^ 


 a| 
*Tipos de disco compatibles*
 a| 
* SSD de propósito general (gp3 y gp2) ^3^,^5^
* SSD de IOPS aprovisionadas (io1) ^3^
* HDD optimizado para rendimiento (st1) ^4^




 a| 
*Nivelación de datos fríos a S3*
 a| 
Compatible

|===
Notas:

. Para un par de HA, el límite de capacidad es para todo el par de HA. No es por nodo. Por ejemplo, si usas la licencia Premium, puedes tener hasta 368 TiB de capacidad entre ambos nodos.
. En algunas configuraciones, los límites de disco impiden que puedas alcanzar el límite de capacidad usando solo discos. En esos casos, puedes alcanzar el límite de capacidad mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["organizar los datos inactivos por niveles en el almacenamiento de objetos"^]. Para obtener información sobre los límites de disco, consulta link:reference-limits-aws.html["límites de almacenamiento"].
+
Con el modelo de licencia basado en capacidad, cada sistema Cloud Volumes ONTAP admite el uso de niveles hacia almacenamiento de objetos. La capacidad total en niveles puede escalar hasta el límite de bucket del proveedor de la nube. Aunque la licencia no impone restricciones de capacidad, deberías seguir la  https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool mejores prácticas"^] para asegurar un rendimiento, fiabilidad y eficiencia de costos óptimos al configurar y gestionar el tiering.

. El rendimiento de escritura mejorado se activa cuando usas SSDs con todas las configuraciones de Cloud Volumes ONTAP.
. No se recomienda clasificar los datos por niveles en el almacenamiento de objetos cuando se utilizan Throughput Optimized HDDs (st1).
. Las configuraciones de Cloud Volumes ONTAP en AWS Local Zones solo soportan el tipo de disco General Purpose SSD (gp2). No se soportan otros tipos de disco en Cloud Volumes ONTAP en AWS Local Zones.


--
.Licencias basadas en nodos
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explore | PAYGO Standard | PAYGO Premium | BYOL basado en nodos 


| Capacidad máxima del sistema (discos + almacenamiento de objetos) | 2 TiB | 10 TiB | 368 TiB ^2^ | 368 TiB por licencia ^2^ 


| Tipos de disco compatibles  a| 
* SSD de propósito general (gp3 y gp2) ^3^,^5^
* SSD de IOPS aprovisionadas (io1) ^3^
* HDD optimizado para rendimiento (st1) ^4^




| Asignación de datos en frío a S3 | No compatible 3+| Compatible 
|===
Notas:

. Para un par de HA, el límite de capacidad es para todo el par de HA. No es por nodo. Por ejemplo, si usas la licencia Premium, puedes tener hasta 368 TiB de capacidad entre ambos nodos.
. En algunas configuraciones, los límites de disco impiden que puedas alcanzar el límite de capacidad usando solo discos. En esos casos, puedes alcanzar el límite de capacidad mediante https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["organizar los datos inactivos por niveles en el almacenamiento de objetos"^]. Para obtener información sobre los límites de disco, consulta link:reference-limits-aws.html["límites de almacenamiento"].
. El rendimiento de escritura mejorado se activa al usar SSDs con todas las configuraciones de Cloud Volumes ONTAP, excepto para PAYGO Explore.
. No se recomienda clasificar los datos por niveles en el almacenamiento de objetos cuando se utilizan Throughput Optimized HDDs (st1).
. Las configuraciones de Cloud Volumes ONTAP en AWS Local Zones solo admiten el tipo de disco General Purpose SSD (gp2).


--
====


[[supported-disk-sizes]]
=== Tamaños de disco compatibles

En AWS, un agregado puede contener hasta 6 discos que son todos del mismo tamaño. Pero si tienes una configuración que soporta la función Amazon EBS Elastic Volumes, entonces un agregado puede contener hasta 8 discos. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-aws-elastic-volumes.html["Obtén más información sobre el soporte para Elastic Volumes"^]

[cols="3*"]
|===
| SSD de uso general (gp3 y gp2) | SSD de IOPS aprovisionadas (io1) | HDD optimizados para rendimiento (st1) 


 a| 
* 100 GiB
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB

 a| 
* 100 GiB
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB

 a| 
* 500 GiB
* 1 TiB
* 2 TiB
* 4 TiB
* 6 TiB
* 8 TiB
* 16 TiB


|===


[[supported-ec2-compute]]
== EC2 compute compatible

Cada licencia de Cloud Volumes ONTAP admite distintos tipos de instancia de EC2. Para tu comodidad, la tabla siguiente muestra las vCPU, RAM y ancho de banda de cada tipo de instancia admitida. https://aws.amazon.com/ec2/instance-types/["Deberías consultar AWS para obtener los detalles más recientes y completos sobre los tipos de instancia EC2"^].

Cloud Volumes ONTAP puede ejecutarse en una instancia EC2 reservada o bajo demanda. Las soluciones que usan otros tipos de instancia no son compatibles.

Los anchos de banda mostrados en la siguiente tabla coinciden con los límites documentados de AWS para cada tipo de instancia. Estos límites no coinciden completamente con lo que Cloud Volumes ONTAP puede proporcionar. Para el rendimiento esperado, consulta https://www.netapp.com/pdf.html?item=/media/9088-tr4383.pdf["NetApp Technical Report 4383: caracterización del rendimiento de Cloud Volumes ONTAP en Amazon Web Services con cargas de trabajo de aplicaciones"^].

[cols="8*"]
|===
| Licencia | Instancia compatible | vCPU | RAM | Flash Cache ^1^ | Ancho de banda de red (Gbps) | Ancho de banda de EBS (Mbps) | Alta velocidad de escritura ^2^ 


| *Explore o cualquier otra licencia* | m5.xlarge ^6^ | 4 | 16 | No compatible | Hasta 10 | Hasta 4,750 | Compatible (solo nodo único) 


.3+| *Estándar o cualquier otra licencia* | r5.xlarge ^6^ | 4 | 32 | No compatible | Hasta 10 | Hasta 4,750 | Compatible (solo nodo único) 


| m5a.2xlarge | 8 | 32 | No compatible | Hasta 10 | Hasta 2,880 | Compatible 


| m5.2xlarge ^6^ | 8 | 32 | No compatible | Hasta 10 | Hasta 4,750 | Compatible 


.22+| *Premium o cualquier otra licencia* | m5n.2xlarge | 8 | 32 | No compatible | Hasta 25 | Hasta 4,750 | Compatible 


| r5.2xlarge ^6^ | 8 | 64 | No compatible | Hasta 10 | Hasta 4,750 | Compatible 


| r5d.2xlarge | 8 | 64 | Compatible | Hasta 10 | Hasta 4,750 | Compatible 


| c5d.4xlarge ^6^ | 16 | 32 | Compatible | Hasta 10 | 4.570 | Compatible 


| m5.4xlarge ^6^ | 16 | 64 | No compatible | Hasta 10 | 4.750 | Compatible 


| m5dn.4xlarge | 16 | 64 | Compatible | Hasta 25 | 4.750 | Compatible 


| m5d.8xlarge | 32 | 128 | Compatible | 10 | 6.800 | Compatible 


| r5.8xlarge | 32 | 256 | No compatible | 10 | 6.800 | Compatible 


| c5.9xlarge | 36 | 72 | No compatible | 10 | 9.500 | Compatible 


| c5d.9xlarge | 36 | 72 | Compatible | 10 | 9.500 | Compatible 


| c5n.9xlarge | 36 | 96 | No compatible | 50 | 9.500 | Compatible 


| c5a.12xlarge | 48 | 96 | No compatible | 12 | 4.750 | Compatible 


| c5.18xlarge | 64 ^4^ | 144 | No compatible | 25 | 19.000 | Compatible 


| c5d.18xlarge | 64 ^4^ | 144 | Compatible | 25 | 19.000 | Compatible 


| m5d.12xlarge | 48 | 192 | Compatible | 12 | 9.500 | Compatible 


| m5dn.12xlarge | 48 | 192 | Compatible | 50 | 9.500 | Compatible 


| c5n.18xlarge | 64 ^4^ | 192 | No compatible | 100 | 19.000 | Compatible 


| m5a.16xlarge | 64 | 256 | No compatible | 12 | 9.500 | Compatible 


| m5.16xlarge | 64 | 256 | No compatible | 20 | 13.600 | Compatible 


| r5.12xlarge ^3^ | 48 | 384 | No compatible | 10 | 9.500 | Compatible 


| m5dn.24xlarge | 64 ^4^ | 384 | Compatible | 100 | 19.000 | Compatible 


| m6id.32xlarge | 64 ^4^ | 512 | Compatible | 50 | 40.000 | Compatible 
|===
. Algunos tipos de instancia incluyen almacenamiento NVMe local, que Cloud Volumes ONTAP utiliza como _Flash Cache_. Flash Cache acelera el acceso a los datos mediante caché inteligente en tiempo real de los datos de usuario leídos recientemente y los metadatos de NetApp. Es eficaz para cargas de trabajo de lectura intensiva aleatoria, incluyendo bases de datos, correo electrónico y servicios de archivos. La compresión debe estar desactivada en todos los volúmenes para aprovechar las mejoras de rendimiento de Flash Cache. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-flash-cache.html["Conoce más sobre Flash Cache"^]
. Cloud Volumes ONTAP admite alta velocidad de escritura con la mayoría de los tipos de instancia cuando usas un par de HA. Se admite alta velocidad de escritura con todos los tipos de instancia cuando usas un sistema de nodo único. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-write-speed.html["Más información sobre cómo elegir una velocidad de escritura"^].
. El tipo de instancia r5.12xlarge tiene una limitación conocida con la capacidad de soporte. Si un nodo se reinicia inesperadamente debido a un pánico, es posible que el sistema no recopile los archivos principales usados para investigar y encontrar la causa del problema. El cliente acepta los riesgos y los términos de soporte limitados y asume toda la responsabilidad de soporte si ocurre esta condición. Esta limitación afecta a los pares de HA recién implementados y a los pares de HA actualizados desde 9.8. La limitación no afecta a los sistemas de nodo único recién implementados.
. Mientras que estos tipos de instancia EC2 admiten más de 64 vCPUs, Cloud Volumes ONTAP solo admite hasta 64 vCPUs.
. Cuando eliges un tipo de instancia EC2, puedes especificar si es una instancia compartida o dedicada.
. AWS Local Zones se admite en las siguientes familias de tipos de instancia EC2 con tamaños de xlarge a 4xlarge: M5, C5, C5d, R5 y R5d. link:https://aws.amazon.com/about-aws/global-infrastructure/localzones/features/?nc=sn&loc=2["Deberías consultar AWS para obtener los detalles más recientes y completos sobre los tipos de instancia EC2 compatibles en Local Zones"^].
+
La alta velocidad de escritura no es compatible con estos tipos de instancia en AWS Local Zones.





[[c4-m4-and-r4-instances-no-longer-supported]]
=== Las instancias c4, m4 y r4 ya no son compatibles

Cloud Volumes ONTAP ya no es compatible con los tipos de instancia c4, m4 y r4 de EC2 en AWS. Si tu sistema se ejecuta en una instancia c4, m4 o r4, cambia a una instancia c5, m5 o r5. No puedes actualizar a esta versión hasta que cambies el tipo de instancia.

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-change-ec2-instance.html["Aprende cómo cambiar el tipo de instancia EC2 para Cloud Volumes ONTAP"^].

Para más información, consulta:

* https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Converting_an_AWS_Xen_CVO_instance_to_Nitro_KVM["Artículo de base de conocimientos (KB): conversión de una instancia AWS Xen CVO a Nitro KVM"^]
* https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/Unable_to_change_the_instance_type_from_r4_to_r5_with_disk_count_error["Artículo KB: no se puede cambiar el tipo de instancia de r4 a r5 con error de recuento de discos"^]
* link:https://mysupport.netapp.com/info/communications/ECMLP2880231.html["Obtén más información sobre el fin de la disponibilidad y el soporte para estos tipos de instancias"^]




[[supported-regions]]
== Regiones compatibles

Para soporte de la región de AWS, consulta https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes regiones globales"^].
