---
sidebar: sidebar 
permalink: reference-configs-gcp.html 
keywords: google, gcp, google cloud platform, explore, standard, premium, byol, paygo, disks, supported, capacity, machine types, sizes, HA, high availability, HA pairs 
summary: Se admiten varias configuraciones de Cloud Volumes ONTAP en Google Cloud. 
---
= Configuraciones compatibles para Cloud Volumes ONTAP en Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Se admiten varias configuraciones de Cloud Volumes ONTAP en Google Cloud.



[[supported-configurations-by-license]]
== Configuraciones admitidas por licencia

Cloud Volumes ONTAP está disponible en Google Cloud como un sistema de nodo único y como un par de nodos de alta disponibilidad (HA) para tolerancia a fallos y operaciones sin interrupciones.

No se admite la actualización de un sistema de nodo único a un par de HA. Si quieres cambiar entre un sistema de nodo único y un par de HA, necesitas implementar un sistema nuevo y replicar los datos del sistema existente al nuevo.

Cloud Volumes ONTAP puede ejecutarse en una instancia de VM reservada o bajo demanda de tu proveedor de cloud. Las soluciones que usan otros tipos de instancia de VM no son compatibles.

[role="tabbed-block"]
====
.Licencias basadas en capacidad
--
[cols="h,d,d,d"]
|===
|  | Freemium | Optimizado ^4^ | Licencia basada en capacidad (Essentials y Professional) 


| Capacidad máxima del sistema (discos + almacenamiento de objetos) | 500 GiB  a| 
Con el modelo de licencia basado en capacidad, cada sistema Cloud Volumes ONTAP admite el uso de niveles hacia almacenamiento de objetos. La capacidad total en niveles puede escalar hasta el límite de bucket del proveedor de la nube. Aunque la licencia no impone restricciones de capacidad, deberías seguir la  https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["FabricPool mejores prácticas"^] para asegurar un rendimiento, fiabilidad y eficiencia de costos óptimos al configurar y gestionar el tiering.



| Tipos de máquinas compatibles ^1^  a| 
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64

 a| 
* n2-standard-4
* n2-standard-8

 a| 
* n1-standard-8 ^1^
* n1-standard-32 ^1^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64




| Tipos de disco compatibles ^2^ 3+| Discos persistentes equilibrados ^3^, discos persistentes de alto rendimiento (SSD) ^3^ y discos persistentes estándar (HDD). 
|===
Notas:

. ^1^ Las máquinas de la serie n1 ya no están disponibles para selección en la NetApp Console al desplegar nuevas instancias de Cloud Volumes ONTAP en Google Cloud. Las máquinas de la serie n1 solo se conservarán y admitirán en sistemas antiguos ya existentes. Los nuevos despliegues de Cloud Volumes ONTAP solo se admiten en Google Cloud a partir de la versión 9.8. Te recomendamos que cambies a las máquinas de la serie n2, que son compatibles con Cloud Volumes ONTAP 9.8 y versiones posteriores. Sin embargo, las máquinas de la serie n1 estarán disponibles para nuevos despliegues realizados a través de la API.
+
El tipo de máquina custom-4-16384 ya no es compatible con los nuevos sistemas Cloud Volumes ONTAP. Si tienes un sistema existente ejecutándose en este tipo de máquina, puedes seguir usándolo, pero te recomendamos cambiar al tipo de máquina n2-standard-4.

. ^2^ Los límites de disco pueden impedir que alcances el límite máximo de capacidad del sistema usando solo discos. Puedes alcanzar el límite de capacidad https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["organizar los datos inactivos por niveles en el almacenamiento de objetos"^].
+
link:reference-limits-gcp.html["Aprende más sobre los límites de disco en Google Cloud"].

. ^3^ El rendimiento de escritura mejorado se activa cuando usas discos persistentes Balanced y discos persistentes Performance (SSD).
+
A partir de Cloud Volumes ONTAP 9.13.0, _Flash Cache_, alta velocidad de escritura y una unidad máxima de transmisión (MTU) de 8,896 bytes, están disponibles para las siguientes instancias de implementación de pares de HA:

+
** n2-standard-16
** n2-standard-32
** n2-standard-48
** n2-standard-64
+
Puedes habilitar _Flash Cache_ y alta velocidad de escritura al desplegar un tipo de instancia elegible. Para habilitar la unidad de transmisión máxima de 8,896 bytes, debes elegir VPC-1, VPC-2 o VPC-3 para el despliegue. La MTU más alta permite un mayor rendimiento de red. Para más información sobre cómo lanzar uno de estos despliegues, consulta https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Lanzar un par de HA en Google Cloud"].

+

NOTE: _Flash Cache_, el modo de alta escritura y una MTU de 8,896 dependen de las características y no pueden desactivarse individualmente en una instancia configurada.



. ^4^ A partir del 11 de agosto de 2025, la licencia Cloud Volumes ONTAP Optimized quedará obsoleta y ya no estará disponible para compra o renovación en el marketplace de Google Cloud para suscripciones de pago por uso (PAYGO). Para información, consulta https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/whats-new.html["Novedades en Cloud Volumes ONTAP"^].


--
.Licencias basadas en nodos
--
[cols="h,d,d,d,d"]
|===
|  | PAYGO Explore | PAYGO Standard | PAYGO Premium | BYOL basado en nodos 


| Capacidad máxima del sistema (discos + almacenamiento de objetos) | 2 TB ^2^ | 10 TiB | 368 TiB | 368 TiB por licencia 


| Tipos de máquinas compatibles ^3^  a| 
* n2-standard-4

 a| 
* n1-standard-8 ^3^
* n2-standard-8

 a| 
* n1-standard-32 ^3^
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64

 a| 
* n1-standard-8 ^3^
* n1-standard-32 ^3^
* n2-standard-4
* n2-standard-8
* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64




| Tipos de disco compatibles 4+| Discos persistentes equilibrados ^4^, discos persistentes de alto rendimiento (SSD) ^4^ y discos persistentes estándar (HDD). 
|===
Notas:

. ^1^ Los límites de disco pueden impedir que alcances el límite máximo de capacidad del sistema usando solo discos. Puedes alcanzar el límite de capacidad https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html["organizar los datos inactivos por niveles en el almacenamiento de objetos"^].
+
link:reference-limits-gcp.html["Aprende más sobre los límites de disco en Google Cloud"].

. ^2^ La organización en niveles de datos a Google Cloud Storage no es compatible con PAYGO Explore.
. ^3^ Las máquinas de la serie n1 ya no están disponibles para selección en la Console al desplegar nuevas instancias de Cloud Volumes ONTAP en Google Cloud. Las máquinas de la serie n1 solo se conservarán y se admitirán en sistemas existentes más antiguos. Los nuevos despliegues de Cloud Volumes ONTAP se admiten en Google Cloud solo a partir de la versión 9.8. Te recomendamos que cambies a las máquinas de la serie n2 que son compatibles con Cloud Volumes ONTAP 9.8 y versiones posteriores. Sin embargo, las máquinas de la serie n1 estarán disponibles para nuevos despliegues realizados a través de la API.
+
El tipo de máquina custom-4-16384 ya no es compatible con los nuevos sistemas Cloud Volumes ONTAP. Si tienes un sistema existente ejecutándose en este tipo de máquina, puedes seguir usándolo, pero te recomendamos cambiar al tipo de máquina n2-standard-4.

. ^4^ El rendimiento de escritura mejorado se activa cuando usas discos persistentes Balanced y discos persistentes Performance (SSD).


La consola muestra un tipo de máquina compatible adicional para Standard y BYOL: n1-highmem-4. Sin embargo, este tipo de máquina no está pensado para entornos de producción. Lo hemos puesto disponible solo para un entorno de laboratorio específico.

A partir de la versión 9.13.0 del software Cloud Volumes ONTAP, _Flash Cache_, alta velocidad de escritura y una unidad máxima de transmisión (MTU) de 8,896 bytes, están disponibles para las siguientes instancias de despliegue de pares de HA:

* n2-standard-16
* n2-standard-32
* n2-standard-48
* n2-standard-64


Puedes habilitar _Flash Cache_ y alta velocidad de escritura al desplegar un tipo de instancia elegible. Para habilitar la unidad de transmisión máxima de 8,896 bytes, debes elegir VPC-1, VPC-2 o VPC-3 para el despliegue. La MTU más alta permite un mayor rendimiento de red. Para más información sobre cómo lanzar uno de estos despliegues, consulta https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-deploying-gcp.html#launching-an-ha-pair-in-google-cloud["Lanzar un par de HA en Google Cloud"].


NOTE: _Flash Cache_, el modo de alta escritura y una MTU de 8,896 dependen de las características y no pueden desactivarse individualmente en una instancia configurada.

--
====
Para obtener más información sobre tipos específicos de máquinas, consulta la documentación de Google Cloud:

* https://cloud.google.com/compute/docs/general-purpose-machines#n1_machines["tipos de máquinas de uso general de la serie n1"^]
* https://cloud.google.com/compute/docs/general-purpose-machines#n2_series["Tipos de máquinas de uso general de la serie N2"^]




[[supported-disk-sizes]]
== Tamaños de disco compatibles

En Google Cloud, un agregado puede contener hasta 6 discos que sean todos del mismo tipo y tamaño. Los siguientes tamaños de disco son compatibles:

* 100 GB
* 500 GB
* 1 TB
* 2 TB
* 4 TB
* 8 TB
* 16 TB
* 64 TB




[[supported-regions]]
== Regiones compatibles

Para soporte de la región de Google Cloud, consulta https://bluexp.netapp.com/cloud-volumes-global-regions["Cloud Volumes regiones globales"^].
